COMPATIBLE_HOST = '(mips.*)-(linux)'

COMPATIBLE_HOST_cube = '(arm.*)-(linux)'
COMPATIBLE_HOST_su980 = '(arm.*)-(linux)'

COMPATIBLE_HOST_sh4 = '(sh4.*)-(linux)'

COMPATIBLE_HOST_wetekplay = '(arm.*)-(linux)'
COMPATIBLE_HOST_x8hp = '(arm.*)-(linux)'

COMPATIBLE_HOST_wetekhub = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_wetekplay2 = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_odroidc2 = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_k1pro = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_k2pro = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_k2prov2 = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_k3pro = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_k1plus = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_kvim2 = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_c300 = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_c300pro = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_c400plus = '(aarch64.*)-(linux)'
COMPATIBLE_HOST_alien5 = '(aarch64.*)-(linux)'
